In [1]:
import pandas as pd 
import re
import numpy as np 
import datetime

# 1970 Decennial Census on 2010 geographies
https://www.socialexplorer.com/data/C1970/metadata/?ds=SEORG&table=PT023

In [3]:
df = pd.read_csv('1970.csv')

In [4]:
df.columns

Index(['Geo_FIPS', 'Geo_NAME', 'Geo_QName', 'Geo_State', 'Geo_COUNTY',
       'Geo_TractCode', 'Geo_TRACT', 'Geo_SUFFTRT', 'Geo_METROARA',
       'Geo_PLACE', 'Geo_URBANARA', 'SEORG_PT023_001', 'SEORG_PT023_002',
       'SEORG_PT023_003', 'SEORG_PT023_004', 'SEORG_PT023_005',
       'SEORG_PT023_006', 'SEORG_PT023_007', 'SEORG_PT023_008',
       'SEORG_PT023_009', 'SEORG_PT023_010', 'SEORG_PT023_011',
       'SEORG_PT023_012', 'SEORG_PT023_013', 'SEORG_PT023_014',
       'SEORG_PT023_015', 'SEORG_PT023_016', 'SEORG_PT023_017',
       'SEORG_PT023_018', 'SEORG_PT023_019', 'SEORG_PT023_020',
       'SEORG_PT023_021', 'SEORG_PT023_022', 'SEORG_PT023_023',
       'SEORG_PT023_024', 'SEORG_PT023_025', 'SEORG_PT023_026',
       'SEORG_PT023_027', 'SEORG_PT023_028', 'SEORG_PT023_029'],
      dtype='object')

In [5]:
# Renaming columns

df.rename(columns={'SEORG_PT023_001': 'count_of_persons', 'SEORG_PT023_003':'native_english', 'SEORG_PT023_004':'native_french', 'SEORG_PT023_005':'native_swedish',\
                  'SEORG_PT023_006':'native_german','SEORG_PT023_007':'native_polish','SEORG_PT023_008':'native_russian','SEORG_PT023_009':'native_hungarian',\
                  'SEORG_PT023_010':'native_yiddish', 'SEORG_PT023_011':'native_italian', 'SEORG_PT023_012':'native_spanish', 'SEORG_PT023_013': 'native_portuguese',\
                  'SEORG_PT023_014':'native_others','SEORG_PT023_015':'native_not_reported', 'SEORG_PT023_017': 'foreign_english', 'SEORG_PT023_018':'foreign_french',\
                  'SEORG_PT023_019':'foreign_swedish','SEORG_PT023_020':'foreign_german','SEORG_PT023_021':'foreign_polish', 'SEORG_PT023_022':'foreign_russian',\
                  'SEORG_PT023_023':'foreign_hungarian', 'SEORG_PT023_024':'foreign_yiddish', 'SEORG_PT023_025':'foreign_italian','SEORG_PT023_026':'foreign_spanish',\
                   'SEORG_PT023_027':'foreign_portuguese','SEORG_PT023_028':'foreign_others','SEORG_PT023_029':'foreign_not_reported'}, inplace=True)

In [6]:
df

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_State,Geo_COUNTY,Geo_TractCode,Geo_TRACT,Geo_SUFFTRT,Geo_METROARA,Geo_PLACE,...,foreign_german,foreign_polish,foreign_russian,foreign_hungarian,foreign_yiddish,foreign_italian,foreign_spanish,foreign_portuguese,foreign_others,foreign_not_reported
0,36005000100,1.0,"Census Tract 1, Bronx County, New York",36,5,100,1,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,9.0,75.0,0.0,9.0,0.0
1,36005000200,2.0,"Census Tract 2, Bronx County, New York",36,5,200,2,NaN,5600,NaN,...,18.0,0.0,0.0,0.0,0.0,59.0,27.0,0.0,8.0,0.0
2,36005000400,4.0,"Census Tract 4, Bronx County, New York",36,5,400,4,NaN,5600,NaN,...,0.0,0.0,0.0,4.0,0.0,47.0,33.0,0.0,33.0,12.0
3,36005001100,11.0,"Census Tract 11, Bronx County, New York",36,5,1100,11,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,79.0,0.0,28.0,0.0
4,36005001500,15.0,"Census Tract 15, Bronx County, New York",36,5,1500,15,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,36005001600,16.0,"Census Tract 16, Bronx County, New York",36,5,1600,16,NaN,5600,NaN,...,8.0,0.0,0.0,0.0,0.0,36.0,14.0,0.0,0.0,8.0
6,36005001700,17.0,"Census Tract 17, Bronx County, New York",36,5,1700,17,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,7.0,188.0,0.0,0.0,0.0
7,36005002000,20.0,"Census Tract 20, Bronx County, New York",36,5,2000,20,NaN,5600,NaN,...,28.0,8.0,38.0,6.0,67.0,154.0,205.0,0.0,52.0,24.0
8,36005002300,23.0,"Census Tract 23, Bronx County, New York",36,5,2300,23,NaN,5600,NaN,...,19.0,0.0,0.0,8.0,16.0,48.0,195.0,0.0,36.0,11.0
9,36005002500,25.0,"Census Tract 25, Bronx County, New York",36,5,2500,25,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,23.0,0.0,178.0,0.0,53.0,0.0
10,36005002701,27.1,"Census Tract 27.1, Bronx County, New York",36,5,2701,27,1.0,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,103.0,0.0,23.0,5.0
11,36005002702,27.2,"Census Tract 27.2, Bronx County, New York",36,5,2702,27,2.0,5600,NaN,...,22.0,0.0,0.0,0.0,15.0,5.0,61.0,6.0,5.0,5.0
12,36005002800,28.0,"Census Tract 28, Bronx County, New York",36,5,2800,28,NaN,5600,NaN,...,7.0,22.0,0.0,25.0,46.0,7.0,108.0,0.0,71.0,7.0
13,36005003100,31.0,"Census Tract 31, Bronx County, New York",36,5,3100,31,NaN,5600,NaN,...,11.0,0.0,0.0,0.0,0.0,0.0,324.0,0.0,10.0,0.0
14,36005003300,33.0,"Census Tract 33, Bronx County, New York",36,5,3300,33,NaN,5600,NaN,...,38.0,8.0,0.0,0.0,13.0,10.0,212.0,4.0,35.0,0.0
15,36005003500,35.0,"Census Tract 35, Bronx County, New York",36,5,3500,35,NaN,5600,NaN,...,8.0,6.0,11.0,0.0,45.0,11.0,93.0,5.0,35.0,0.0
16,36005003600,36.0,"Census Tract 36, Bronx County, New York",36,5,3600,36,NaN,5600,NaN,...,40.0,25.0,14.0,20.0,165.0,83.0,151.0,0.0,101.0,13.0
17,36005003700,37.0,"Census Tract 37, Bronx County, New York",36,5,3700,37,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,7.0,7.0,0.0,37.0,0.0
18,36005003800,38.0,"Census Tract 38, Bronx County, New York",36,5,3800,38,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,20.0,6.0,0.0,0.0,8.0
19,36005003900,39.0,"Census Tract 39, Bronx County, New York",36,5,3900,39,NaN,5600,NaN,...,53.0,11.0,0.0,0.0,0.0,0.0,341.0,0.0,18.0,13.0
20,36005004001,40.1,"Census Tract 40.1, Bronx County, New York",36,5,4001,40,1.0,5600,NaN,...,22.0,0.0,0.0,0.0,11.0,90.0,10.0,0.0,62.0,0.0
21,36005004100,41.0,"Census Tract 41, Bronx County, New York",36,5,4100,41,NaN,5600,NaN,...,14.0,7.0,6.0,6.0,32.0,0.0,104.0,0.0,14.0,6.0
22,36005004300,43.0,"Census Tract 43, Bronx County, New York",36,5,4300,43,NaN,5600,NaN,...,43.0,0.0,0.0,21.0,0.0,41.0,263.0,10.0,28.0,12.0
23,36005004400,44.0,"Census Tract 44, Bronx County, New York",36,5,4400,44,NaN,5600,NaN,...,8.0,5.0,22.0,0.0,173.0,81.0,51.0,0.0,77.0,8.0
24,36005004600,46.0,"Census Tract 46, Bronx County, New York",36,5,4600,46,NaN,5600,NaN,...,8.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,17.0,0.0
25,36005004700,47.0,"Census Tract 47, Bronx County, New York",36,5,4700,47,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,7.0,0.0,27.0,0.0,0.0,0.0
26,36005004800,48.0,"Census Tract 48, Bronx County, New York",36,5,4800,48,NaN,5600,NaN,...,13.0,0.0,18.0,0.0,78.0,96.0,365.0,8.0,33.0,16.0
27,36005004900,49.0,"Census Tract 49, Bronx County, New York",36,5,4900,49,NaN,5600,NaN,...,7.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,16.0,0.0
28,36005005000,50.0,"Census Tract 50, Bronx County, New York",36,5,5000,50,NaN,5600,NaN,...,89.0,35.0,41.0,57.0,270.0,112.0,700.0,0.0,102.0,16.0
29,36005005200,52.0,"Census Tract 52, Bronx County, New York",36,5,5200,52,NaN,5600,NaN,...,24.0,6.0,6.0,0.0,32.0,23.0,47.0,0.0,8.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,36085018701,187.1,"Census Tract 187.1, Richmond County, New York",36,85,18701,187,1.0,5600,NaN,...,5.0,0.0,14.0,8.0,0.0,0.0,0.0,0.0,62.0,0.0
2138,36085018702,187.2,"Census Tract 187.2, Richmond County, New York",36,85,18702,187,2.0,5600,NaN,...,11.0,43.0,8.0,0.0,22.0,214.0,33.0,0.0,64.0,0.0
2139,36085018901,189.1,"Census Tract 189.1, Richmond County, New York",36,85,18901,189,1.0,5600,NaN,...,39.0,7.0,0.0,7.0,9.0,180.0,43.0,0.0,79.0,0.0
2140,36085018902,189.2,"Census Tract 189.2, Richmond County, New York",36,85,18902,189,2.0,5600,NaN,...,24.0,0.0,0.0,0.0,15.0,134.0,0.0,0.0,6.0,0.0
2141,36085019600,196.0,"Census Tract 196, Richmond County, New York",36,85,19600,196,NaN,5600,NaN,...,61.0,9.0,0.0,0.0,0.0,25.0,6.0,0.0,76.0,0.0
2142,36085019700,197.0,"Census Tract 197, Richmond County, New York",36,85,19700,197,NaN,5600,NaN,...,13.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,109.0,0.0
2143,36085020100,201.0,"Census Tract 201, Richmond County, New York",36,85,20100,201,NaN,5600,NaN,...,25.0,0.0,0.0,0.0,0.0,64.0,34.0,0.0,101.0,5.0
2144,36085020700,207.0,"Census Tract 207, Richmond County, New York",36,85,20700,207,NaN,5600,NaN,...,14.0,12.0,0.0,0.0,0.0,85.0,116.0,0.0,122.0,0.0
2145,36085020801,208.1,"Census Tract 208.1, Richmond County, New York",36,85,20801,208,1.0,5600,NaN,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0
2146,36085020802,208.2,"Census Tract 208.2, Richmond County, New York",36,85,20802,208,2.0,5600,NaN,...,0.0,14.0,0.0,0.0,12.0,35.0,7.0,0.0,81.0,0.0
2147,36085021300,213.0,"Census Tract 213, Richmond County, New York",36,85,21300,213,NaN,5600,NaN,...,66.0,81.0,0.0,0.0,0.0,157.0,24.0,0.0,114.0,22.0
2148,36085021900,219.0,"Census Tract 219, Richmond County, New York",36,85,21900,219,NaN,5600,NaN,...,7.0,22.0,0.0,0.0,0.0,0.0,11.0,0.0,4.0,0.0
2149,36085022300,223.0,"Census Tract 223, Richmond County, New York",36,85,22300,223,NaN,5600,NaN,...,7.0,17.0,0.0,0.0,0.0,60.0,0.0,0.0,52.0,0.0
2150,36085022600,226.0,"Census Tract 226, Richmond County, New York",36,85,22600,226,NaN,5600,NaN,...,6.0,0.0,0.0,28.0,0.0,0.0,12.0,0.0,33.0,0.0
2151,36085023100,231.0,"Census Tract 231, Richmond County, New York",36,85,23100,231,NaN,5600,NaN,...,0.0,0.0,0.0,8.0,0.0,139.0,0.0,0.0,19.0,16.0
2152,36085023600,236.0,"Census Tract 236, Richmond County, New York",36,85,23600,236,NaN,5600,NaN,...,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,14.0,0.0
2153,36085023900,239.0,"Census Tract 239, Richmond County, New York",36,85,23900,239,NaN,5600,NaN,...,14.0,103.0,0.0,0.0,11.0,75.0,0.0,0.0,47.0,8.0
2154,36085024400,244.0,"Census Tract 244, Richmond County, New York",36,85,24400,244,NaN,5600,NaN,...,22.0,0.0,0.0,0.0,0.0,9.0,7.0,0.0,61.0,0.0
2155,36085024700,247.0,"Census Tract 247, Richmond County, New York",36,85,24700,247,NaN,5600,NaN,...,6.0,23.0,0.0,0.0,0.0,83.0,0.0,0.0,86.0,0.0
2156,36085024800,248.0,"Census Tract 248, Richmond County, New York",36,85,24800,248,NaN,5600,NaN,...,22.0,21.0,0.0,19.0,0.0,25.0,14.0,0.0,23.0,0.0
2157,36085025100,251.0,"Census Tract 251, Richmond County, New York",36,85,25100,251,NaN,5600,NaN,...,20.0,6.0,0.0,0.0,0.0,77.0,0.0,0.0,46.0,0.0
2158,36085027301,273.1,"Census Tract 273.1, Richmond County, New York",36,85,27301,273,1.0,5600,NaN,...,0.0,13.0,0.0,9.0,0.0,28.0,0.0,0.0,13.0,0.0
2159,36085027302,273.2,"Census Tract 273.2, Richmond County, New York",36,85,27302,273,2.0,5600,NaN,...,0.0,13.0,0.0,0.0,0.0,24.0,5.0,0.0,41.0,0.0
2160,36085027700,277.0,"Census Tract 277, Richmond County, New York",36,85,27700,277,NaN,5600,NaN,...,13.0,20.0,0.0,0.0,0.0,15.0,15.0,0.0,55.0,0.0
2161,36085027900,279.0,"Census Tract 279, Richmond County, New York",36,85,27900,279,NaN,5600,NaN,...,13.0,6.0,7.0,0.0,0.0,31.0,0.0,0.0,53.0,0.0
2162,36085029100,291.0,"Census Tract 291, Richmond County, New York",36,85,29100,291,NaN,5600,NaN,...,10.0,18.0,0.0,5.0,19.0,121.0,9.0,0.0,79.0,6.0
2163,36085030300,303.0,"Census Tract 303, Richmond County, New York",36,85,30300,303,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,8.0,15.0,0.0,0.0,24.0,0.0
2164,36085031901,319.1,"Census Tract 319.1, Richmond County, New York",36,85,31901,319,1.0,5600,NaN,...,32.0,0.0,0.0,0.0,0.0,43.0,77.0,0.0,69.0,0.0
2165,36085031902,319.2,"Census Tract 319.2, Richmond County, New York",36,85,31902,319,2.0,5600,NaN,...,15.0,6.0,8.0,0.0,10.0,11.0,0.0,0.0,54.0,7.0
2166,36085032300,323.0,"Census Tract 323, Richmond County, New York",36,85,32300,323,NaN,5600,NaN,...,3.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0

In [7]:
df.columns

Index(['Geo_FIPS', 'Geo_NAME', 'Geo_QName', 'Geo_State', 'Geo_COUNTY',
       'Geo_TractCode', 'Geo_TRACT', 'Geo_SUFFTRT', 'Geo_METROARA',
       'Geo_PLACE', 'Geo_URBANARA', 'count_of_persons', 'SEORG_PT023_002',
       'native_english', 'native_french', 'native_swedish', 'native_german',
       'native_polish', 'native_russian', 'native_hungarian', 'native_yiddish',
       'native_italian', 'native_spanish', 'native_portuguese',
       'native_others', 'native_not_reported', 'SEORG_PT023_016',
       'foreign_english', 'foreign_french', 'foreign_swedish',
       'foreign_german', 'foreign_polish', 'foreign_russian',
       'foreign_hungarian', 'foreign_yiddish', 'foreign_italian',
       'foreign_spanish', 'foreign_portuguese', 'foreign_others',
       'foreign_not_reported'],
      dtype='object')

I'll want to calculate things, but BY NEIGHBORHOOD I'M INTERESTED IN

I want to get the info for 
- Astoria
- Borough Park
- Another one with Italian or Russian? Russian

In [8]:
df[df.Geo_QName.str.contains('Queens')]

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_State,Geo_COUNTY,Geo_TractCode,Geo_TRACT,Geo_SUFFTRT,Geo_METROARA,Geo_PLACE,...,foreign_german,foreign_polish,foreign_russian,foreign_hungarian,foreign_yiddish,foreign_italian,foreign_spanish,foreign_portuguese,foreign_others,foreign_not_reported
1409,36081000100,1.0,"Census Tract 1, Queens County, New York",36,81,100,1,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0
1410,36081000200,2.0,"Census Tract 2, Queens County, New York",36,81,200,2,NaN,5600,NaN,...,109.0,14.0,10.0,0.0,0.0,48.0,0.0,0.0,108.0,0.0
1411,36081000400,4.0,"Census Tract 4, Queens County, New York",36,81,400,4,NaN,5600,NaN,...,95.0,0.0,0.0,0.0,14.0,157.0,53.0,0.0,102.0,0.0
1412,36081000600,6.0,"Census Tract 6, Queens County, New York",36,81,600,6,NaN,5600,NaN,...,45.0,24.0,5.0,0.0,0.0,101.0,22.0,23.0,52.0,0.0
1413,36081000700,7.0,"Census Tract 7, Queens County, New York",36,81,700,7,NaN,5600,NaN,...,57.0,0.0,0.0,0.0,0.0,701.0,302.0,0.0,60.0,7.0
1414,36081000800,8.0,"Census Tract 8, Queens County, New York",36,81,800,8,NaN,5600,NaN,...,58.0,15.0,0.0,7.0,0.0,113.0,0.0,0.0,11.0,12.0
1415,36081001000,10.0,"Census Tract 10, Queens County, New York",36,81,1000,10,NaN,5600,NaN,...,35.0,8.0,0.0,0.0,9.0,134.0,0.0,0.0,41.0,7.0
1416,36081001200,12.0,"Census Tract 12, Queens County, New York",36,81,1200,12,NaN,5600,NaN,...,115.0,13.0,0.0,7.0,32.0,134.0,20.0,0.0,115.0,0.0
1417,36081001400,14.0,"Census Tract 14, Queens County, New York",36,81,1400,14,NaN,5600,NaN,...,122.0,8.0,18.0,0.0,15.0,177.0,4.0,0.0,144.0,0.0
1418,36081001600,16.0,"Census Tract 16, Queens County, New York",36,81,1600,16,NaN,5600,NaN,...,74.0,6.0,0.0,8.0,0.0,124.0,0.0,0.0,121.0,0.0
1419,36081001800,18.0,"Census Tract 18, Queens County, New York",36,81,1800,18,NaN,5600,NaN,...,31.0,59.0,0.0,0.0,21.0,42.0,7.0,0.0,34.0,15.0
1420,36081001900,19.0,"Census Tract 19, Queens County, New York",36,81,1900,19,NaN,5600,NaN,...,47.0,0.0,0.0,0.0,0.0,20.0,101.0,14.0,8.0,0.0
1421,36081002000,20.0,"Census Tract 20, Queens County, New York",36,81,2000,20,NaN,5600,NaN,...,50.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,43.0,0.0
1422,36081002200,22.0,"Census Tract 22, Queens County, New York",36,81,2200,22,NaN,5600,NaN,...,44.0,15.0,12.0,0.0,81.0,85.0,13.0,0.0,105.0,0.0
1423,36081002400,24.0,"Census Tract 24, Queens County, New York",36,81,2400,24,NaN,5600,NaN,...,123.0,0.0,0.0,0.0,0.0,17.0,12.0,0.0,18.0,0.0
1424,36081002500,25.0,"Census Tract 25, Queens County, New York",36,81,2500,25,NaN,5600,NaN,...,51.0,36.0,6.0,39.0,45.0,79.0,130.0,7.0,101.0,0.0
1425,36081002600,26.0,"Census Tract 26, Queens County, New York",36,81,2600,26,NaN,5600,NaN,...,51.0,16.0,7.0,16.0,12.0,64.0,14.0,0.0,57.0,0.0
1426,36081002700,27.0,"Census Tract 27, Queens County, New York",36,81,2700,27,NaN,5600,NaN,...,0.0,0.0,4.0,0.0,0.0,53.0,46.0,0.0,48.0,0.0
1427,36081002800,28.0,"Census Tract 28, Queens County, New York",36,81,2800,28,NaN,5600,NaN,...,32.0,0.0,47.0,0.0,6.0,93.0,0.0,0.0,79.0,0.0
1428,36081002900,29.0,"Census Tract 29, Queens County, New York",36,81,2900,29,NaN,5600,NaN,...,14.0,0.0,0.0,0.0,0.0,45.0,73.0,0.0,56.0,9.0
1429,36081003000,30.0,"Census Tract 30, Queens County, New York",36,81,3000,30,NaN,5600,NaN,...,69.0,6.0,14.0,22.0,0.0,5.0,33.0,0.0,26.0,0.0
1430,36081003100,31.0,"Census Tract 31, Queens County, New York",36,81,3100,31,NaN,5600,NaN,...,11.0,5.0,0.0,0.0,0.0,119.0,0.0,0.0,40.0,5.0
1431,36081003200,32.0,"Census Tract 32, Queens County, New York",36,81,3200,32,NaN,5600,NaN,...,14.0,29.0,0.0,0.0,12.0,43.0,0.0,0.0,15.0,0.0
1432,36081003400,34.0,"Census Tract 34, Queens County, New York",36,81,3400,34,NaN,5600,NaN,...,47.0,15.0,0.0,10.0,0.0,16.0,0.0,0.0,0.0,0.0
1433,36081003500,35.0,"Census Tract 35, Queens County, New York",36,81,3500,35,NaN,5600,NaN,...,7.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0
1434,36081003600,36.0,"Census Tract 36, Queens County, New York",36,81,3600,36,NaN,5600,NaN,...,42.0,47.0,6.0,0.0,0.0,188.0,5.0,5.0,29.0,0.0
1435,36081003800,38.0,"Census Tract 38, Queens County, New York",36,81,3800,38,NaN,5600,NaN,...,36.0,68.0,0.0,5.0,4.0,109.0,14.0,0.0,29.0,0.0
1436,36081003900,39.0,"Census Tract 39, Queens County, New York",36,81,3900,39,NaN,5600,NaN,...,0.0,0.0,0.0,0.0,0.0,117.0,13.0,39.0,42.0,0.0
1437,36081004001,40.1,"Census Tract 40.1, Queens County, New York",36,81,4001,40,1.0,5600,NaN,...,38.0,0.0,0.0,8.0,0.0,309.0,7.0,0.0,22.0,5.0
1438,36081004002,40.2,"Census Tract 40.2, Queens County, New York",36,81,4002,40,2.0,5600,NaN,...,5.0,6.0,0.0,0.0,0.0,69.0,0.0,0.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,36081140300,1403.0,"Census Tract 1403, Queens County, New York",36,81,140300,1403,NaN,5600,NaN,...,111.0,18.0,0.0,8.0,80.0,31.0,27.0,0.0,85.0,8.0
2040,36081140901,1409.1,"Census Tract 1409.1, Queens County, New York",36,81,140901,1409,1.0,5600,NaN,...,41.0,7.0,0.0,53.0,6.0,28.0,6.0,0.0,32.0,0.0
2041,36081140902,1409.2,"Census Tract 1409.2, Queens County, New York",36,81,140902,1409,2.0,5600,NaN,...,57.0,13.0,13.0,26.0,70.0,73.0,14.0,8.0,53.0,21.0
2042,36081141701,1417.1,"Census Tract 1417.1, Queens County, New York",36,81,141701,1417,1.0,5600,NaN,...,64.0,40.0,26.0,32.0,134.0,111.0,51.0,0.0,56.0,6.0
2043,36081141702,1417.2,"Census Tract 1417.2, Queens County, New York",36,81,141702,1417,2.0,5600,NaN,...,0.0,0.0,28.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
2044,36081142900,1429.0,"Census Tract 1429, Queens County, New York",36,81,142900,1429,NaN,5600,NaN,...,79.0,24.0,6.0,37.0,35.0,182.0,6.0,0.0,125.0,0.0
2045,36081143500,1435.0,"Census Tract 1435, Queens County, New York",36,81,143500,1435,NaN,5600,NaN,...,142.0,24.0,0.0,9.0,5.0,27.0,59.0,10.0,70.0,0.0
2046,36081144100,1441.0,"Census Tract 1441, Queens County, New York",36,81,144100,1441,NaN,5600,NaN,...,104.0,19.0,20.0,10.0,102.0,115.0,18.0,0.0,122.0,5.0
2047,36081144700,1447.0,"Census Tract 1447, Queens County, New York",36,81,144700,1447,NaN,5600,NaN,...,79.0,38.0,5.0,7.0,38.0,85.0,40.0,0.0,12.0,10.0
2048,36081145101,1451.1,"Census Tract 1451.1, Queens County, New York",36,81,145101,1451,1.0,5600,NaN,...,21.0,4.0,5.0,6.0,0.0,81.0,8.0,0.0,26.0,0.0
2049,36081145102,1451.2,"Census Tract 1451.2, Queens County, New York",36,81,145102,1451,2.0,5600,NaN,...,4.0,22.0,18.0,10.0,34.0,94.0,33.0,0.0,86.0,0.0
2050,36081145900,1459.0,"Census Tract 1459, Queens County, New York",36,81,145900,1459,NaN,5600,NaN,...,33.0,12.0,0.0,39.0,21.0,136.0,0.0,0.0,31.0,0.0
2051,36081146300,1463.0,"Census Tract 1463, Queens County, New York",36,81,146300,1463,NaN,5600,NaN,...,69.0,0.0,0.0,0.0,10.0,262.0,21.0,0.0,32.0,5.0
2052,36081146700,1467.0,"Census Tract 1467, Queens County, New York",36,81,146700,1467,NaN,5600,NaN,...,56.0,0.0,8.0,0.0,18.0,134.0,39.0,12.0,153.0,0.0
2053,36081147100,1471.0,"Census Tract 1471, Queens County, New York",36,81,147100,1471,NaN,5600,NaN,...,83.0,57.0,0.0,30.0,62.0,51.0,33.0,0.0,109.0,0.0
2054,36081147900,1479.0,"Census Tract 1479, Queens County, New York",36,81,147900,1479,NaN,5600,NaN,...,76.0,38.0,0.0,4.0,25.0,111.0,12.0,0.0,93.0,18.0
2055,36081148300,1483.0,"Census Tract 1483, Queens County, New York",36,81,148300,1483,NaN,5600,NaN,...,79.0,0.0,0.0,10.0,0.0,14.0,0.0,0.0,30.0,0.0
2056,36081150701,1507.1,"Census Tract 1507.1, Queens County, New York",36,81,150701,1507,1.0,5600,NaN,...,143.0,0.0,19.0,14.0,9.0,58.0,34.0,0.0,74.0,0.0
2057,36081150702,1507.2,"Census Tract 1507.2, Queens County, New York",36,81,150702,1507,2.0,5600,NaN,...,29.0,39.0,14.0,0.0,57.0,41.0,0.0,0.0,82.0,0.0
2058,36081152901,1529.1,"Census Tract 1529.1, Queens County, New York",36,81,152901,1529,1.0,5600,NaN,...,106.0,46.0,11.0,7.0,106.0,54.0,31.0,0.0,32.0,4.0
2059,36081152902,1529.2,"Census Tract 1529.2, Queens County, New York",36,81,152902,1529,2.0,5600,NaN,...,97.0,46.0,24.0,0.0,287.0,53.0,23.0,0.0,115.0,7.0
2060,36081155100,1551.0,"Census Tract 1551, Queens County, New York",36,81,155100,1551,NaN,5600,NaN,...,154.0,62.0,18.0,7.0,153.0,78.0,64.0,0.0,190.0,0.0
2061,36081156700,1567.0,"Census Tract 1567, Queens County, New York",36,81,156700,1567,NaN,5600,NaN,...,80.0,80.0,118.0,34.0,0.0,138.0,29.0,0.0,186.0,42.0
2062,36081157101,1571.1,"Census Tract 1571.1, Queens County, New York",36,81,157101,1571,1.0,5600,NaN,...,194.0,34.0,76.0,13.0,141.0,188.0,8.0,14.0,61.0,0.0
2063,36081157102,1571.2,"Census Tract 1571.2, Queens County, New York",36,81,157102,1571,2.0,5600,NaN,...,50.0,0.0,6.0,26.0,0.0,53.0,0.0,0.0,16.0,0.0
2064,36081157901,1579.1,"Census Tract 1579.1, Queens County, New York",36,81,157901,1579,1.0,5600,NaN,...,111.0,25.0,6.0,7.0,48.0,79.0,12.0,0.0,133.0,5.0
2065,36081157902,1579.2,"Census Tract 1579.2, Queens County, New York",36,81,157902,1579,2.0,5600,NaN,...,130.0,52.0,14.0,7.0,85.0,142.0,15.0,0.0,106.0,0.0
2066,36081157903,1579.3,"Census Tract 1579.3, Queens County, New York",36,81,157903,1579,3.0,5600,NaN,...,176.0,8.0,14.0,0.0,15.0,74.0,32.0,0.0,93.0,7.0
2067,36081161700,1617.0,"Census Tract 1617, Queens County, New York",36,81,161700,1617,NaN,5600,NaN,...,148.0,18.0,0.0,6.0,0.0,65.0,56.0,0.0,45.0,0.0
2068,36081162100,1621.0,"Census Tract 1621, Queens County, New York",36,81,162100,1621,NaN,5600,NaN,...,126.0,11.0,0.0,0.0,6.0,131.0,57.0,0.0,89.0,14.0

So FIRST, let's do this for Astoria. I'll want to get the census tracts in the neighborhood.

In [9]:
# Let's read in census tracts!

In [10]:
census_tracts = pd.read_csv('conversion_table.csv')

In [11]:
census_tracts.head()

,Borough,2010 Census Bureau FIPS County Code,2010 NYC Borough Code,2010 Census Tract,PUMA,Neighborhood Tabulation Area (NTA)Code,Neighborhood Tabulation Area (NTA) Name
0,Bronx,5,2,31000,3704,BX31,Allerton-Pelham Gardens
1,Bronx,5,2,31200,3704,BX31,Allerton-Pelham Gardens
2,Bronx,5,2,31400,3704,BX31,Allerton-Pelham Gardens
3,Bronx,5,2,31600,3704,BX31,Allerton-Pelham Gardens
4,Bronx,5,2,31800,3704,BX31,Allerton-Pelham Gardens

In [12]:
astoria = census_tracts[census_tracts['Neighborhood Tabulation Area (NTA) Name'].str.contains('Astoria')]

In [13]:
astoria.head()

,Borough,2010 Census Bureau FIPS County Code,2010 NYC Borough Code,2010 Census Tract,PUMA,Neighborhood Tabulation Area (NTA)Code,Neighborhood Tabulation Area (NTA) Name
1390,Queens,81,4,4500,4101,QN70,Astoria
1391,Queens,81,4,4700,4101,QN70,Astoria
1392,Queens,81,4,5300,4101,QN70,Astoria
1393,Queens,81,4,5700,4101,QN70,Astoria
1394,Queens,81,4,5900,4101,QN70,Astoria

In [14]:
astoria['geo_fips'] = astoria['2010 Census Tract']

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [15]:
astoria['geo_fips'] = astoria['geo_fips'].astype(str)

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [16]:
astoria

,Borough,2010 Census Bureau FIPS County Code,2010 NYC Borough Code,2010 Census Tract,PUMA,Neighborhood Tabulation Area (NTA)Code,Neighborhood Tabulation Area (NTA) Name,geo_fips
1390,Queens,81,4,4500,4101,QN70,Astoria,4500
1391,Queens,81,4,4700,4101,QN70,Astoria,4700
1392,Queens,81,4,5300,4101,QN70,Astoria,5300
1393,Queens,81,4,5700,4101,QN70,Astoria,5700
1394,Queens,81,4,5900,4101,QN70,Astoria,5900
1395,Queens,81,4,6100,4101,QN70,Astoria,6100
1396,Queens,81,4,6300,4101,QN70,Astoria,6300
1397,Queens,81,4,6501,4101,QN70,Astoria,6501
1398,Queens,81,4,6502,4101,QN70,Astoria,6502
1399,Queens,81,4,7500,4101,QN70,Astoria,7500
1400,Queens,81,4,7700,4101,QN70,Astoria,7700
1401,Queens,81,4,14100,4101,QN70,Astoria,14100
1402,Queens,81,4,14300,4101,QN70,Astoria,14300
1403,Queens,81,4,14500,4101,QN70,Astoria,14500
1404,Queens,81,4,14700,4101,QN70,Astoria,14700
1405,Queens,81,4,14900,4101,QN70,Astoria,14900
1406,Queens,81,4,15100,4101,QN70,Astoria,15100
1407,Queens,81,4,15300,4101,QN70,Astoria,15300
1408,Queens,81,4,15500,4101,QN70,Astoria,15500
1409,Queens,81,4,15700,4101,QN70,Astoria,15700
1410,Queens,81,4,15900,4101,QN70,Astoria,15900
1411,Queens,81,4,16100,4101,QN70,Astoria,16100
1412,Queens,81,4,16300,4101,QN70,Astoria,16300
1800,Queens,81,4,6900,4101,QN71,Old Astoria,6900
1801,Queens,81,4,7100,4101,QN71,Old Astoria,7100
1802,Queens,81,4,7300,4101,QN71,Old Astoria,7300
1803,Queens,81,4,7900,4101,QN71,Old Astoria,7900
1804,Queens,81,4,8100,4101,QN71,Old Astoria,8100
1805,Queens,81,4,8300,4101,QN71,Old Astoria,8300
1806,Queens,81,4,8700,4101,QN71,Old Astoria,8700
1807,Queens,81,4,9100,4101,QN71,Old Astoria,9100

In [17]:
# Converting everything
astoria['geo_fips'] = '360810' + astoria['geo_fips'].str.zfill(5)

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [18]:
geo_to_look_for = astoria.geo_fips.tolist()

In [19]:
astoria_languages = df[df.Geo_FIPS.isin(geo_to_look_for)]

In [20]:
# 29 census tracts for Astoria!
# So now we have this, we can sum the total population that speaks english, etc etc.

In [21]:
df_sum=pd.DataFrame(data=astoria_languages.sum()).T

In [22]:
df_sum.columns

Index(['Geo_FIPS', 'Geo_NAME', 'Geo_QName', 'Geo_State', 'Geo_COUNTY',
       'Geo_TractCode', 'Geo_TRACT', 'Geo_SUFFTRT', 'Geo_METROARA',
       'Geo_PLACE', 'Geo_URBANARA', 'count_of_persons', 'SEORG_PT023_002',
       'native_english', 'native_french', 'native_swedish', 'native_german',
       'native_polish', 'native_russian', 'native_hungarian', 'native_yiddish',
       'native_italian', 'native_spanish', 'native_portuguese',
       'native_others', 'native_not_reported', 'SEORG_PT023_016',
       'foreign_english', 'foreign_french', 'foreign_swedish',
       'foreign_german', 'foreign_polish', 'foreign_russian',
       'foreign_hungarian', 'foreign_yiddish', 'foreign_italian',
       'foreign_spanish', 'foreign_portuguese', 'foreign_others',
       'foreign_not_reported'],
      dtype='object')

In [23]:
# Now let's calculate percentages
df_sum['perc_english'] = (df_sum.native_english + df_sum.foreign_english) / df_sum.count_of_persons * 100
df_sum['perc_french'] = (df_sum.native_french + df_sum.foreign_french) / df_sum.count_of_persons * 100
df_sum['perc_swedish'] = (df_sum.native_swedish + df_sum.foreign_swedish) / df_sum.count_of_persons * 100
df_sum['perc_german'] = (df_sum.native_german + df_sum.foreign_german) / df_sum.count_of_persons * 100
df_sum['perc_polish'] = (df_sum.native_polish + df_sum.foreign_polish) / df_sum.count_of_persons * 100
df_sum['perc_russian'] = (df_sum.native_russian + df_sum.foreign_russian) / df_sum.count_of_persons * 100
df_sum['perc_hungarian'] = (df_sum.native_hungarian + df_sum.foreign_hungarian) / df_sum.count_of_persons * 100
df_sum['perc_yiddish'] = (df_sum.native_yiddish + df_sum.foreign_yiddish) / df_sum.count_of_persons * 100
df_sum['perc_italian'] = (df_sum.native_italian + df_sum.foreign_italian) / df_sum.count_of_persons * 100
df_sum['perc_spanish'] = (df_sum.native_spanish + df_sum.foreign_spanish) / df_sum.count_of_persons * 100
df_sum['perc_portuguese'] = (df_sum.native_portuguese + df_sum.foreign_portuguese) / df_sum.count_of_persons * 100
df_sum['perc_others'] = (df_sum.native_others + df_sum.foreign_others) / df_sum.count_of_persons * 100
df_sum['perc_not_reported'] = (df_sum.native_not_reported + df_sum.foreign_not_reported) / df_sum.count_of_persons * 100

In [24]:
df_sum.filter(like='perc', axis=1)

,perc_english,perc_french,perc_swedish,perc_german,perc_polish,perc_russian,perc_hungarian,perc_yiddish,perc_italian,perc_spanish,perc_portuguese,perc_others,perc_not_reported
0,41.4495,1.73542,0.141405,5.1598,1.30429,0.46278,0.878095,2.35049,15.6109,8.67119,0.178981,16.1716,5.88561

## Borough Park

In [25]:
bp = census_tracts[census_tracts['Neighborhood Tabulation Area (NTA) Name'].str.contains('Borough Park')]

In [26]:
bp['geo_fips'] = bp['2010 Census Tract']
bp['geo_fips'] = bp['geo_fips'].astype(str)

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [27]:
bp['geo_fips'] = '360470' + bp['geo_fips'].str.zfill(5)

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [28]:
geo_to_look_for = bp.geo_fips.tolist()

In [29]:
bp_languages = df[df.Geo_FIPS.isin(geo_to_look_for)]

In [30]:
bp_sum=pd.DataFrame(data=bp_languages.sum()).T

In [31]:
# Now let's calculate percentages
bp_sum['perc_english'] = (bp_sum.native_english + bp_sum.foreign_english) / bp_sum.count_of_persons * 100
bp_sum['perc_french'] = (bp_sum.native_french + bp_sum.foreign_french) / bp_sum.count_of_persons * 100
bp_sum['perc_swedish'] = (bp_sum.native_swedish + bp_sum.foreign_swedish) / bp_sum.count_of_persons * 100
bp_sum['perc_german'] = (bp_sum.native_german + bp_sum.foreign_german) / bp_sum.count_of_persons * 100
bp_sum['perc_polish'] = (bp_sum.native_polish + bp_sum.foreign_polish) / bp_sum.count_of_persons * 100
bp_sum['perc_russian'] = (bp_sum.native_russian + bp_sum.foreign_russian) / bp_sum.count_of_persons * 100
bp_sum['perc_hungarian'] = (bp_sum.native_hungarian + bp_sum.foreign_hungarian) / bp_sum.count_of_persons * 100
bp_sum['perc_yiddish'] = (bp_sum.native_yiddish + bp_sum.foreign_yiddish) / bp_sum.count_of_persons * 100
bp_sum['perc_italian'] = (bp_sum.native_italian + bp_sum.foreign_italian) / bp_sum.count_of_persons * 100
bp_sum['perc_spanish'] = (bp_sum.native_spanish + bp_sum.foreign_spanish) / bp_sum.count_of_persons * 100
bp_sum['perc_portuguese'] = (bp_sum.native_portuguese + bp_sum.foreign_portuguese) / bp_sum.count_of_persons * 100
bp_sum['perc_others'] = (bp_sum.native_others + bp_sum.foreign_others) / bp_sum.count_of_persons * 100
bp_sum['perc_not_reported'] = (bp_sum.native_not_reported + bp_sum.foreign_not_reported) / bp_sum.count_of_persons * 100

In [33]:
bp_sum.filter(like='perc', axis=1)

,perc_english,perc_french,perc_swedish,perc_german,perc_polish,perc_russian,perc_hungarian,perc_yiddish,perc_italian,perc_spanish,perc_portuguese,perc_others,perc_not_reported
0,32.0687,0.60434,0.135493,2.18079,1.61946,0.781771,2.55823,22.7681,21.1164,4.80246,0.0290341,7.93707,3.39807

## Jamaica

In [157]:
flushing = census_tracts[census_tracts['Neighborhood Tabulation Area (NTA) Name'].str.contains('Jamaica')]

In [159]:
flushing = flushing[~ flushing['Neighborhood Tabulation Area (NTA) Name'].str.contains('Estates')]

In [160]:
flushing['geo_fips'] = flushing['2010 Census Tract']
flushing['geo_fips'] = flushing['geo_fips'].astype(str)
flushing['geo_fips'] = '360810' + flushing['geo_fips'].str.zfill(5)

In [161]:
geo_to_look_for = flushing.geo_fips.tolist()
flushing_languages = df[df.Geo_FIPS.isin(geo_to_look_for)]
flushing_sum=pd.DataFrame(data=flushing_languages.sum()).T

In [162]:
flushing_sum

,Geo_FIPS,Geo_NAME,Geo_QName,Geo_State,Geo_COUNTY,Geo_TractCode,Geo_TRACT,Geo_SUFFTRT,Geo_METROARA,Geo_PLACE,...,foreign_german,foreign_polish,foreign_russian,foreign_hungarian,foreign_yiddish,foreign_italian,foreign_spanish,foreign_portuguese,foreign_others,foreign_not_reported
0,1334998186206,11862.6,"Census Tract 196, Queens County, New YorkCensu...",1332,2997,1186206,11862,6,207200,None,...,2116,676,389,257,1382,1820,5113,585,4746,155

In [163]:
# Now let's calculate percentages
flushing_sum['perc_english'] = (flushing_sum.native_english + flushing_sum.foreign_english) / flushing_sum.count_of_persons * 100
flushing_sum['perc_french'] = (flushing_sum.native_french + flushing_sum.foreign_french) / flushing_sum.count_of_persons * 100
flushing_sum['perc_swedish'] = (flushing_sum.native_swedish + flushing_sum.foreign_swedish) / flushing_sum.count_of_persons * 100
flushing_sum['perc_german'] = (flushing_sum.native_german + flushing_sum.foreign_german) / flushing_sum.count_of_persons * 100
flushing_sum['perc_polish'] = (flushing_sum.native_polish + flushing_sum.foreign_polish) / flushing_sum.count_of_persons * 100
flushing_sum['perc_russian'] = (flushing_sum.native_russian + flushing_sum.foreign_russian) / flushing_sum.count_of_persons * 100
flushing_sum['perc_hungarian'] = (flushing_sum.native_hungarian + flushing_sum.foreign_hungarian) / flushing_sum.count_of_persons * 100
flushing_sum['perc_yiddish'] = (flushing_sum.native_yiddish + flushing_sum.foreign_yiddish) / flushing_sum.count_of_persons * 100
flushing_sum['perc_italian'] = (flushing_sum.native_italian + flushing_sum.foreign_italian) / flushing_sum.count_of_persons * 100
flushing_sum['perc_spanish'] = (flushing_sum.native_spanish + flushing_sum.foreign_spanish) / flushing_sum.count_of_persons * 100
flushing_sum['perc_portuguese'] = (flushing_sum.native_portuguese + flushing_sum.foreign_portuguese) / flushing_sum.count_of_persons * 100
flushing_sum['perc_others'] = (flushing_sum.native_others + flushing_sum.foreign_others) / flushing_sum.count_of_persons * 100
flushing_sum['perc_not_reported'] = (flushing_sum.native_not_reported + flushing_sum.foreign_not_reported) / flushing_sum.count_of_persons * 100

In [164]:
flushing_sum.filter(like='perc', axis=1)

,perc_english,perc_french,perc_swedish,perc_german,perc_polish,perc_russian,perc_hungarian,perc_yiddish,perc_italian,perc_spanish,perc_portuguese,perc_others,perc_not_reported
0,54.8687,1.93277,0.151547,4.62767,1.88884,0.580929,0.411812,5.07682,5.22397,9.82309,0.854372,7.85517,6.7043

# Tokenizing text because I'm really lazy

In [11]:
from textblob import TextBlob

In [13]:
excerpt ="それは何年も前だった海の王国で、あなたがアナベル・リーとこの女の名前で知っているかもしれない乙女がそこに住んでいたことは、私に愛し愛されていた"

In [14]:
def tokenize(sentence):
    blob = TextBlob(sentence.lower())
    words = [token for token in blob.words if len(token)>1]
    return words

In [15]:
tokenize(excerpt)

['それは何年も前だった海の王国で、あなたがアナベル・リーとこの女の名前で知っているかもしれない乙女がそこに住んでいたことは、私に愛し愛されていた']

# Astoria in 2016

In [217]:
df_astoria = pd.read_csv('all_simplified.csv')

In [218]:
df_astoria.head()

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,other_asian,tagalog,other_pacific_island,navajo,other_native_na,hungarian,arabic,hebrew,african_lang,others_unspec
0,1400000US36005000100,36005000100,"Census Tract 1, Bronx County, New York",7703,5391,2087,7,31,8,8,...,0,0,7,0,0,0,8,0,16,0
1,1400000US36005000200,36005000200,"Census Tract 2, Bronx County, New York",5107,1546,3243,0,0,0,0,...,0,0,0,0,0,0,0,0,158,0
2,1400000US36005000400,36005000400,"Census Tract 4, Bronx County, New York",5540,2554,2771,103,11,0,0,...,7,0,0,0,0,0,0,0,93,0
3,1400000US36005001600,36005001600,"Census Tract 16, Bronx County, New York",5529,1837,2956,94,11,0,0,...,0,0,0,0,0,0,0,0,622,0
4,1400000US36005001900,36005001900,"Census Tract 19, Bronx County, New York",2376,977,1191,55,22,0,2,...,0,0,0,0,0,0,0,0,5,0

In [219]:
astoria = census_tracts[census_tracts['Neighborhood Tabulation Area (NTA) Name'].str.contains('Astoria')]

In [220]:
astoria

,Borough,2010 Census Bureau FIPS County Code,2010 NYC Borough Code,2010 Census Tract,PUMA,Neighborhood Tabulation Area (NTA)Code,Neighborhood Tabulation Area (NTA) Name
1390,Queens,81,4,4500,4101,QN70,Astoria
1391,Queens,81,4,4700,4101,QN70,Astoria
1392,Queens,81,4,5300,4101,QN70,Astoria
1393,Queens,81,4,5700,4101,QN70,Astoria
1394,Queens,81,4,5900,4101,QN70,Astoria
1395,Queens,81,4,6100,4101,QN70,Astoria
1396,Queens,81,4,6300,4101,QN70,Astoria
1397,Queens,81,4,6501,4101,QN70,Astoria
1398,Queens,81,4,6502,4101,QN70,Astoria
1399,Queens,81,4,7500,4101,QN70,Astoria
1400,Queens,81,4,7700,4101,QN70,Astoria
1401,Queens,81,4,14100,4101,QN70,Astoria
1402,Queens,81,4,14300,4101,QN70,Astoria
1403,Queens,81,4,14500,4101,QN70,Astoria
1404,Queens,81,4,14700,4101,QN70,Astoria
1405,Queens,81,4,14900,4101,QN70,Astoria
1406,Queens,81,4,15100,4101,QN70,Astoria
1407,Queens,81,4,15300,4101,QN70,Astoria
1408,Queens,81,4,15500,4101,QN70,Astoria
1409,Queens,81,4,15700,4101,QN70,Astoria
1410,Queens,81,4,15900,4101,QN70,Astoria
1411,Queens,81,4,16100,4101,QN70,Astoria
1412,Queens,81,4,16300,4101,QN70,Astoria
1800,Queens,81,4,6900,4101,QN71,Old Astoria
1801,Queens,81,4,7100,4101,QN71,Old Astoria
1802,Queens,81,4,7300,4101,QN71,Old Astoria
1803,Queens,81,4,7900,4101,QN71,Old Astoria
1804,Queens,81,4,8100,4101,QN71,Old Astoria
1805,Queens,81,4,8300,4101,QN71,Old Astoria
1806,Queens,81,4,8700,4101,QN71,Old Astoria
1807,Queens,81,4,9100,4101,QN71,Old Astoria

In [221]:
astoria['geo_fips'] = astoria['2010 Census Tract']
astoria['geo_fips'] = astoria['geo_fips'].astype(str)
astoria['geo_fips'] = '360810' + astoria['geo_fips'].str.zfill(5)

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/mariepatino/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [222]:
astoria.head()

,Borough,2010 Census Bureau FIPS County Code,2010 NYC Borough Code,2010 Census Tract,PUMA,Neighborhood Tabulation Area (NTA)Code,Neighborhood Tabulation Area (NTA) Name,geo_fips
1390,Queens,81,4,4500,4101,QN70,Astoria,36081004500
1391,Queens,81,4,4700,4101,QN70,Astoria,36081004700
1392,Queens,81,4,5300,4101,QN70,Astoria,36081005300
1393,Queens,81,4,5700,4101,QN70,Astoria,36081005700
1394,Queens,81,4,5900,4101,QN70,Astoria,36081005900

In [223]:
geo_to_look_for = astoria.geo_fips.tolist()
astoria_languages = df_astoria[df_astoria.Id2.isin(geo_to_look_for)]
astoria_sum=pd.DataFrame(data=astoria_languages.sum()).T

In [241]:
astoria_languages['greek'].sum()

4547

In [242]:
astoria_languages['total_pop'].sum()

102050

In [243]:
4547 / 102050

0.044556589906908375

In [225]:
astoria_sum.columns

Index(['Id', 'Id2', 'Geography', 'total_pop', 'english',
       'spanish_spanish_creole', 'french', 'french_creole', 'italian',
       'portuguese', 'german', 'yiddish', 'other_west_german',
       'scandinavian_langs', 'greek', 'russian', 'polish', 'serbo_croation',
       'other_slavic', 'armenian', 'persian', 'gujarati', 'hindi', 'urdu',
       'other_hindic', 'other_indo_european', 'chinese', 'japanese', 'korean',
       'mon_khmer_cambodian', 'hmong', 'thai', 'laotian', 'vietnamese',
       'other_asian', 'tagalog', 'other_pacific_island', 'navajo',
       'other_native_na', 'hungarian', 'arabic', 'hebrew', 'african_lang',
       'others_unspec'],
      dtype='object')

In [229]:
# Now let's calculate percentages
astoria_sum['perc_english'] = (astoria_sum.english) / astoria_sum.total_pop * 100
astoria_sum['perc_french'] = (astoria_sum.french) / astoria_sum.total_pop * 100
astoria_sum['perc_spanish'] = (astoria_sum.spanish_spanish_creole) / astoria_sum.total_pop * 100
astoria_sum['perc_french_creole'] = (astoria_sum.french_creole ) / astoria_sum.total_pop * 100
astoria_sum['italian'] = (astoria_sum.italian) / astoria_sum.total_pop * 100
astoria_sum['perc_portuguese'] = (astoria_sum.portuguese ) / astoria_sum.total_pop * 100
astoria_sum['perc_german'] = (astoria_sum.german) / astoria_sum.total_pop * 100
astoria_sum['perc_yiddish'] = (astoria_sum.yiddish ) / astoria_sum.total_pop * 100
#astoria_sum['perc_others'] = (astoria_sum.other_west_german + astoria_sum.other_slavic + \
#                             + astoria_sum.other_hindic + astoria_sum.other_indo_european + \
#                             astoria_sum.other_asian + astoria_sum.other_pacific_island + \
#                             astoria_sum.other_native_na + astoria_sum.others_unspec) / astoria_sum.total_pop * 100
astoria_sum['perc_scandinavian'] = (astoria_sum.scandinavian_langs ) / astoria_sum.total_pop * 100
astoria_sum['perc_greek'] = (astoria_sum.greek ) / astoria_sum.total_pop * 100
astoria_sum['perc_russian'] = (astoria_sum.russian ) / astoria_sum.total_pop * 100
astoria_sum['perc_polish'] = (astoria_sum.polish ) / astoria_sum.total_pop * 100
astoria_sum['perc_serbo_croatian'] = (astoria_sum.serbo_croation ) / astoria_sum.total_pop * 100
astoria_sum['perc_armenian'] = (astoria_sum.armenian ) / astoria_sum.total_pop * 100
astoria_sum['perc_persian'] = (astoria_sum.persian ) / astoria_sum.total_pop * 100
astoria_sum['perc_gujarati'] = (astoria_sum.gujarati ) / astoria_sum.total_pop * 100
astoria_sum['perc_hindi'] = (astoria_sum.hindi ) / astoria_sum.total_pop * 100
astoria_sum['perc_urdu'] = (astoria_sum.urdu ) / astoria_sum.total_pop * 100
astoria_sum['perc_chinese'] = (astoria_sum.chinese ) / astoria_sum.total_pop * 100
astoria_sum['perc_japanese'] = (astoria_sum.japanese ) / astoria_sum.total_pop * 100
astoria_sum['perc_korean'] = (astoria_sum.korean ) / astoria_sum.total_pop * 100
astoria_sum['perc_mon_khmer_cambodian'] = (astoria_sum.mon_khmer_cambodian ) / astoria_sum.total_pop * 100
astoria_sum['perc_hmong'] = (astoria_sum.hmong ) / astoria_sum.total_pop * 100
astoria_sum['perc_thai'] = (astoria_sum.thai ) / astoria_sum.total_pop * 100
astoria_sum['perc_laotian'] = (astoria_sum.laotian ) / astoria_sum.total_pop * 100
astoria_sum['perc_vietnamese'] = (astoria_sum.vietnamese ) / astoria_sum.total_pop * 100
astoria_sum['perc_tagalog'] = (astoria_sum.tagalog ) / astoria_sum.total_pop * 100
astoria_sum['perc_navajo'] = (astoria_sum.navajo ) / astoria_sum.total_pop * 100
astoria_sum['perc_hungarian'] = (astoria_sum.hungarian ) / astoria_sum.total_pop * 100
astoria_sum['perc_arabic'] = (astoria_sum.arabic ) / astoria_sum.total_pop * 100
astoria_sum['perc_hebrew'] = (astoria_sum.hebrew ) / astoria_sum.total_pop * 100
astoria_sum['perc_african_lang'] = (astoria_sum.african_lang ) / astoria_sum.total_pop * 100

In [230]:
astoria_sum

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,perc_hmong,perc_thai,perc_laotian,perc_vietnamese,perc_tagalog,perc_navajo,perc_hungarian,perc_arabic,perc_hebrew,perc_african_lang
0,1400000US360810045001400000US36081004700140000...,1118511312503,"Census Tract 45, Queens County, New YorkCensus...",102050,42949,25260,1135,77,0.00172169,2159,...,0,0.459579,0,0.236159,1.22391,0,0.141107,2.34983,0.22244,0.149927

In [234]:
astoria_sum['perc_others'] = (float(astoria_sum.other_west_german) + float(astoria_sum.other_slavic) + \
                             + float(astoria_sum.other_hindic) + float(astoria_sum.other_indo_european) + \
                             float(astoria_sum.other_asian) + float(astoria_sum.other_pacific_island) + \
                             float(astoria_sum.other_native_na) + float(astoria_sum.others_unspec)) / astoria_sum.total_pop * 100

In [236]:
astoria_sum.filter(like='perc', axis=1)

,perc_english,perc_french,perc_spanish,perc_french_creole,perc_portuguese,perc_german,perc_yiddish,perc_scandinavian,perc_greek,perc_russian,...,perc_thai,perc_laotian,perc_vietnamese,perc_tagalog,perc_navajo,perc_hungarian,perc_arabic,perc_hebrew,perc_african_lang,perc_others
0,42.0862,1.1122,24.7526,0.0754532,2.11563,0.365507,0.0705537,0.11563,4.45566,0.67124,...,0.459579,0,0.236159,1.22391,0,0.141107,2.34983,0.22244,0.149927,8.35865

In [245]:
astoria_sum.to_csv('astoria_stats.csv', index=False)

# Calculating the Language Diversity Index

In [17]:
df_ldi = pd.read_csv('all_simplified.csv')

In [18]:
df_ldi.head()

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,other_asian,tagalog,other_pacific_island,navajo,other_native_na,hungarian,arabic,hebrew,african_lang,others_unspec
0,1400000US36005000100,36005000100,"Census Tract 1, Bronx County, New York",7703,5391,2087,7,31,8,8,...,0,0,7,0,0,0,8,0,16,0
1,1400000US36005000200,36005000200,"Census Tract 2, Bronx County, New York",5107,1546,3243,0,0,0,0,...,0,0,0,0,0,0,0,0,158,0
2,1400000US36005000400,36005000400,"Census Tract 4, Bronx County, New York",5540,2554,2771,103,11,0,0,...,7,0,0,0,0,0,0,0,93,0
3,1400000US36005001600,36005001600,"Census Tract 16, Bronx County, New York",5529,1837,2956,94,11,0,0,...,0,0,0,0,0,0,0,0,622,0
4,1400000US36005001900,36005001900,"Census Tract 19, Bronx County, New York",2376,977,1191,55,22,0,2,...,0,0,0,0,0,0,0,0,5,0

In [20]:
df_ldi.columns

Index(['Id', 'Id2', 'Geography', 'total_pop', 'english',
       'spanish_spanish_creole', 'french', 'french_creole', 'italian',
       'portuguese', 'german', 'yiddish', 'other_west_german',
       'scandinavian_langs', 'greek', 'russian', 'polish', 'serbo_croation',
       'other_slavic', 'armenian', 'persian', 'gujarati', 'hindi', 'urdu',
       'other_hindic', 'other_indo_european', 'chinese', 'japanese', 'korean',
       'mon_khmer_cambodian', 'hmong', 'thai', 'laotian', 'vietnamese',
       'other_asian', 'tagalog', 'other_pacific_island', 'navajo',
       'other_native_na', 'hungarian', 'arabic', 'hebrew', 'african_lang',
       'others_unspec'],
      dtype='object')

In [21]:
df_ldi['ldi'] = 1-((df_ldi.english/df_ldi.total_pop)**2 + (df_ldi.spanish_spanish_creole/df_ldi.total_pop)**2 + \
(df_ldi.french/df_ldi.total_pop)**2 + (df_ldi.french_creole/df_ldi.total_pop)**2 + (df_ldi.italian/df_ldi.total_pop)**2 + \
(df_ldi.portuguese/df_ldi.total_pop)**2 + (df_ldi.german/df_ldi.total_pop)**2 + (df_ldi.yiddish/df_ldi.total_pop)**2 + \
(df_ldi.scandinavian_langs/df_ldi.total_pop)**2 + (df_ldi.greek/df_ldi.total_pop)**2 + (df_ldi.russian/df_ldi.total_pop)**2 + \
(df_ldi.polish/df_ldi.total_pop)**2 + (df_ldi.serbo_croation/df_ldi.total_pop)**2 + (df_ldi.armenian/df_ldi.total_pop)**2 + \
(df_ldi.persian/df_ldi.total_pop)**2 + (df_ldi.gujarati/df_ldi.total_pop)**2 + (df_ldi.hindi/df_ldi.total_pop)**2 + \
(df_ldi.urdu/df_ldi.total_pop)**2 + (df_ldi.chinese/df_ldi.total_pop)**2 + (df_ldi.japanese/df_ldi.total_pop)**2  + \
(df_ldi.korean/df_ldi.total_pop)**2 + (df_ldi.mon_khmer_cambodian/df_ldi.total_pop)**2 + (df_ldi.hmong/df_ldi.total_pop)**2 + \
(df_ldi.thai/df_ldi.total_pop)**2 + (df_ldi.laotian/df_ldi.total_pop)**2 + (df_ldi.vietnamese/df_ldi.total_pop)**2  + \
(df_ldi.tagalog/df_ldi.total_pop)**2 + (df_ldi.navajo/df_ldi.total_pop)**2 + (df_ldi.hungarian/df_ldi.total_pop)**2 + \
(df_ldi.arabic/df_ldi.total_pop)**2 + (df_ldi.hebrew/df_ldi.total_pop)**2 + (df_ldi.african_lang/df_ldi.total_pop)**2 + \
(df_ldi.other_west_german/df_ldi.total_pop)**2 + (df_ldi.other_slavic/df_ldi.total_pop)**2 + (df_ldi.other_hindic/df_ldi.total_pop)**2 + \
(df_ldi.other_indo_european/df_ldi.total_pop)**2 + (df_ldi.other_asian/df_ldi.total_pop)**2 + (df_ldi.other_pacific_island/df_ldi.total_pop)**2 + \
(df_ldi.other_native_na/df_ldi.total_pop)**2 + (df_ldi.others_unspec/df_ldi.total_pop)**2)

In [22]:
df_ldi

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,tagalog,other_pacific_island,navajo,other_native_na,hungarian,arabic,hebrew,african_lang,others_unspec,ldi
0,1400000US36005000100,36005000100,"Census Tract 1, Bronx County, New York",7703,5391,2087,7,31,8,8,...,0,7,0,0,0,8,0,16,0,0.436716
1,1400000US36005000200,36005000200,"Census Tract 2, Bronx County, New York",5107,1546,3243,0,0,0,0,...,0,0,0,0,0,0,0,158,0,0.503639
2,1400000US36005000400,36005000400,"Census Tract 4, Bronx County, New York",5540,2554,2771,103,11,0,0,...,0,0,0,0,0,0,0,93,0,0.536655
3,1400000US36005001600,36005001600,"Census Tract 16, Bronx County, New York",5529,1837,2956,94,11,0,0,...,0,0,0,0,0,0,0,622,0,0.590825
4,1400000US36005001900,36005001900,"Census Tract 19, Bronx County, New York",2376,977,1191,55,22,0,2,...,0,0,0,0,0,0,0,5,0,0.578292
5,1400000US36005002000,36005002000,"Census Tract 20, Bronx County, New York",7976,3940,3804,33,33,0,0,...,0,0,0,0,0,0,0,53,0,0.528367
6,1400000US36005002300,36005002300,"Census Tract 23, Bronx County, New York",4371,1662,2542,25,0,0,0,...,0,0,0,0,0,0,0,113,29,0.516465
7,1400000US36005002400,36005002400,"Census Tract 24, Bronx County, New York",150,150,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000
8,1400000US36005002500,36005002500,"Census Tract 25, Bronx County, New York",4907,1512,3195,0,0,0,22,...,7,0,0,0,0,0,0,39,9,0.480669
9,1400000US36005002701,36005002701,"Census Tract 27.01, Bronx County, New York",2759,844,1612,125,0,0,0,...,0,0,0,0,0,0,0,133,45,0.560407
10,1400000US36005002702,36005002702,"Census Tract 27.02, Bronx County, New York",4518,1651,2738,25,7,0,0,...,0,0,0,0,0,0,0,0,97,0.498708
11,1400000US36005002800,36005002800,"Census Tract 28, Bronx County, New York",5038,3626,1067,0,38,0,0,...,0,0,0,0,0,0,0,138,0,0.435201
12,1400000US36005003100,36005003100,"Census Tract 31, Bronx County, New York",1383,223,1006,55,0,0,0,...,7,0,0,0,0,0,0,73,0,0.440302
13,1400000US36005003300,36005003300,"Census Tract 33, Bronx County, New York",3611,1390,2048,0,0,0,0,...,0,0,0,0,0,0,0,173,0,0.527864
14,1400000US36005003500,36005003500,"Census Tract 35, Bronx County, New York",3550,966,2388,36,6,8,0,...,0,0,0,0,0,0,0,146,0,0.471659
15,1400000US36005003700,36005003700,"Census Tract 37, Bronx County, New York",246,95,124,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.584738
16,1400000US36005003800,36005003800,"Census Tract 38, Bronx County, New York",1101,559,459,19,0,31,0,...,0,0,0,0,0,0,0,28,0,0.566662
17,1400000US36005003900,36005003900,"Census Tract 39, Bronx County, New York",5748,1200,4389,13,0,0,0,...,0,0,0,0,0,0,0,35,111,0.372962
18,1400000US36005004001,36005004001,"Census Tract 40.01, Bronx County, New York",1322,454,525,0,0,9,0,...,0,0,0,0,0,37,0,0,0,0.708502
19,1400000US36005004100,36005004100,"Census Tract 41, Bronx County, New York",6033,2323,3608,0,54,0,0,...,0,0,0,0,0,28,0,0,0,0.493973
20,1400000US36005004200,36005004200,"Census Tract 42, Bronx County, New York",6599,4049,2310,11,0,0,0,...,13,0,0,0,0,0,19,150,0,0.500403
21,1400000US36005004300,36005004300,"Census Tract 43, Bronx County, New York",5414,1752,3455,120,0,0,0,...,0,0,0,0,0,0,0,79,0,0.487325
22,1400000US36005004400,36005004400,"Census Tract 44, Bronx County, New York",4430,2360,2027,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.506799
23,1400000US36005004600,36005004600,"Census Tract 46, Bronx County, New York",1738,938,798,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0.497904
24,1400000US36005004800,36005004800,"Census Tract 48, Bronx County, New York",3640,1157,2299,0,27,0,0,...,0,0,0,0,0,18,0,62,0,0.499354
25,1400000US36005005001,36005005001,"Census Tract 50.01, Bronx County, New York",4535,1964,2335,68,29,0,0,...,0,0,0,0,0,0,0,139,0,0.546134
26,1400000US36005005002,36005005002,"Census Tract 50.02, Bronx County, New York",5164,1212,3571,130,62,0,0,...,9,0,0,0,0,14,0,166,0,0.464896
27,1400000US36005005100,36005005100,"Census Tract 51, Bronx County, New York",5136,2220,2904,0,9,0,0,...,0,0,0,0,0,0,0,3,0,0.493462
28,1400000US36005005200,36005005200,"Census Tract 52, Bronx County, New York",2100,800,1257,4,33,0,0,...,0,0,0,0,0,0,0,0,0,0.496329
29,1400000US36005005300,36005005300,"Census Tract 53, Bronx County, New York",3447,1919,1341,40,0,0,0,...,0,0,0,0,0,0,0,147,0,0.536767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,1400000US36085020801,36085020801,"Census Tract 208.01, Richmond County, New York",8660,7038,224,0,0,573,0,...,0,0,0,0,0,42,0,0,0,0.333166
2138,1400000US36085020803,36085020803,"Census Tract 208.03, Richmond County, New York",5780,4325,310,0,0,229,0,...,12,0,0,0,0,0,286,0,0,0.430038
2139,1400000US36085020804,36085020804,"Census Tract 208.04, Richmond County, New York",5291,4224,42,44,0,227,0,...,0,0,0,0,0,41,0,0,0,0.357306
2140,1400000US36085021300,36085021300,"Census Tract 213, Richmond County, New York",4479,2714,1319,17,0,14,0,...,58,0,0,0,0,0,0,75,0,0.544446
2141,1400000US36085022300,36085022300,"Census Tract 223, Richmond County, New York",2402,1549,498,21,0,22,12,...,14,0,0,0,0,58,93,50,0,0.538034
2142,1400000US36085022600,36085022600,"Census Tract 226, Richmond County, New York",8614,5754,1485,23,10,284,0,...,57,9,0,0,0,49,8,0,0,0.517300
2143,1400000US36085022800,36085022800,"Census Tract 228, Richmond County, New York",35,35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000
2144,1400000US36085023100,36085023100,"Census Tract 231, Richmond County, New York",4087,2210,1059,8,23,0,0,...,0,8,0,0,0,98,0,113,0,0.633815
2145,1400000US36085023900,36085023900,"Census Tract 239, Richmond County, New York",3090,1248,1567,39,0,0,0,...,64,0,0,20,0,0,0,0,0,0.578582
2146,1400000US36085024401,36085024401,"Census Tract 244.01, Richmond County, New York",6073,5449,124,0,0,159,0,...,18,0,0,0,0,42,0,0,0,0.193204
2147,1400000US36085024402,36085024402,"Census Tract 244.02, Richmond County, New York",4005,2986,107,0,0,218,39,...,0,28,0,0,0,136,0,0,0,0.436648
2148,1400000US36085024700,36085024700,"Census Tract 247, Richmond County, New York",2555,1580,653,79,22,15,0,...,49,0,0,0,14,21,0,16,0,0.549661
2149,1400000US36085024800,36085024800,"Census Tract 248, Richmond County, New York",4673,4229,162,11,0,129,7,...,0,0,0,0,0,65,0,0,0,0.178743
2150,1400000US36085025100,36085025100,"Census Tract 251, Richmond County, New York",5574,4772,222,21,0,124,0,...,118,0,0,0,0,25,0,0,0,0.263881
2151,1400000US36085027301,36085027301,"Census Tract 273.01, Richmond County, New York",3629,2311,51,34,0,185,0,...,146,0,0,0,0,127,7,0,0,0.578423
2152,1400000US36085027302,36085027302,"Census Tract 273.02, Richmond County, New York",3103,2078,168,47,0,63,0,...,28,0,0,0,10,53,145,0,0,0.541446
2153,1400000US36085027702,36085027702,"Census Tract 277.02, Richmond County, New York",6160,3822,711,0,0,159,0,...,158,0,0,0,0,0,0,22,0,0.590470
2154,1400000US36085027704,36085027704,"Census Tract 277.04, Richmond County, New York",4139,2547,130,0,0,109,0,...,0,0,0,0,0,455,39,0,0,0.592906
2155,1400000US36085027705,36085027705,"Census Tract 277.05, Richmond County, New York",5352,3086,169,0,0,231,0,...,102,0,0,0,0,286,274,25,0,0.644590
2156,1400000US36085027706,36085027706,"Census Tract 277.06, Richmond County, New York",3404,2265,84,0,0,31,0,...,7,0,0,0,0,94,89,0,0,0.545171
2157,1400000US36085027900,36085027900,"Census Tract 279, Richmond County, New York",1902,1586,77,0,8,63,0,...,13,0,0,7,25,12,0,0,0,0.300680
2158,1400000US36085029102,36085029102,"Census Tract 291.02, Richmond County, New York",2577,1860,295,0,0,76,0,...,44,0,0,0,0,142,4,0,0,0.460701
2159,1400000US36085029103,36085029103,"Census Tract 291.03, Richmond County, New York",7357,5496,389,0,0,294,0,...,38,5,0,0,0,97,0,0,32,0.432922
2160,1400000US36085029104,36085029104,"Census Tract 291.04, Richmond County, New York",6760,4897,486,0,0,77,0,...,10,0,0,0,0,143,0,199,0,0.464437
2161,1400000US36085030301,36085030301,"Census Tract 303.01, Richmond County, New York",4668,2708,891,0,0,46,0,...,106,0,0,0,0,73,0,44,0,0.620973
2162,1400000US36085030302,36085030302,"Census Tract 303.02, Richmond County, New York",5831,3006,1292,34,0,12,0,...,273,0,0,0,0,393,0,115,0,0.675185
2163,1400000US36085031901,36085031901,"Census Tract 319.01, Richmond County, New York",2392,1622,392,56,0,0,0,...,30,0,0,0,0,74,0,101,0,0.508445
2164,1400000US36085031902,36085031902,"Census Tract 319.02, Richmond County, New York",4101,2977,766,28,0,11,0,...,12,0,0,0,0,42,0,198,0,0.435581
2165,1400000US36085032300,36085032300,"Census Tract 323, Richmond County, New York",1038,676,354,0,0,0,0,...,0,0,0,0,0,0,0,8,0,0.459502
2166,1400000US36085990100,36085990100,"Census Tract 9901, Richmond County, New York",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

In [23]:
# When 0 say no data
# When NaN say no data
df_ldi.ldi = df_ldi.ldi.fillna(0)

In [24]:
df_ldi.ldi

0       0.436716
1       0.503639
2       0.536655
3       0.590825
4       0.578292
5       0.528367
6       0.516465
7       0.000000
8       0.480669
9       0.560407
10      0.498708
11      0.435201
12      0.440302
13      0.527864
14      0.471659
15      0.584738
16      0.566662
17      0.372962
18      0.708502
19      0.493973
20      0.500403
21      0.487325
22      0.506799
23      0.497904
24      0.499354
25      0.546134
26      0.464896
27      0.493462
28      0.496329
29      0.536767
          ...
2137    0.333166
2138    0.430038
2139    0.357306
2140    0.544446
2141    0.538034
2142    0.517300
2143    0.000000
2144    0.633815
2145    0.578582
2146    0.193204
2147    0.436648
2148    0.549661
2149    0.178743
2150    0.263881
2151    0.578423
2152    0.541446
2153    0.590470
2154    0.592906
2155    0.644590
2156    0.545171
2157    0.300680
2158    0.460701
2159    0.432922
2160    0.464437
2161    0.620973
2162    0.675185
2163    0.508445
2164    0.435581
2165    0.459502
2166    0.000000
Name: ldi, Length: 2167, dtype: float64

In [25]:
df_ldi.to_csv('census_tracts_with_ldi.csv', index=False)

# BP

In [34]:
# BP 2016
geo_to_look_for

['36047011400',
 '36047011600',
 '36047019200',
 '36047021400',
 '36047021600',
 '36047021800',
 '36047022000',
 '36047022200',
 '36047022400',
 '36047022600',
 '36047022800',
 '36047023000',
 '36047023200',
 '36047023400',
 '36047023600',
 '36047023800',
 '36047024000',
 '36047024200',
 '36047024400',
 '36047024600',
 '36047044600',
 '36047046400',
 '36047046800',
 '36047047000',
 '36047047200',
 '36047047400',
 '36047047600',
 '36047047800']

In [35]:
df_bp_2016 = pd.read_csv('all_simplified.csv')

In [36]:
bp_languages_2016 = df_bp_2016[df_bp_2016.Id2.isin(geo_to_look_for)]

In [37]:
bp_languages_2016

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,other_asian,tagalog,other_pacific_island,navajo,other_native_na,hungarian,arabic,hebrew,african_lang,others_unspec
417,1400000US36047011400,36047011400,"Census Tract 114, Kings County, New York",3945,919,474,9,11,0,0,...,9,74,12,0,0,134,22,134,10,0
418,1400000US36047011600,36047011600,"Census Tract 116, Kings County, New York",3895,405,351,0,0,10,0,...,116,2,45,0,0,7,57,16,0,0
486,1400000US36047019200,36047019200,"Census Tract 192, Kings County, New York",3072,826,294,0,0,36,0,...,9,59,0,0,12,6,41,128,0,0
507,1400000US36047021400,36047021400,"Census Tract 214, Kings County, New York",2105,372,55,0,0,60,0,...,0,0,0,0,0,33,34,35,0,0
509,1400000US36047021600,36047021600,"Census Tract 216, Kings County, New York",3950,746,232,7,0,62,0,...,0,9,0,0,0,41,59,89,0,0
511,1400000US36047021800,36047021800,"Census Tract 218, Kings County, New York",3787,488,328,5,0,0,21,...,0,0,0,0,0,121,34,55,0,0
513,1400000US36047022000,36047022000,"Census Tract 220, Kings County, New York",3679,620,392,51,0,0,0,...,0,0,0,0,0,95,0,148,0,0
515,1400000US36047022200,36047022200,"Census Tract 222, Kings County, New York",3753,595,404,0,0,0,75,...,8,0,0,0,0,9,0,283,0,0
516,1400000US36047022400,36047022400,"Census Tract 224, Kings County, New York",4992,1173,1026,0,0,63,0,...,0,0,0,0,0,2,0,65,0,0
517,1400000US36047022600,36047022600,"Census Tract 226, Kings County, New York",2138,425,1335,0,0,37,0,...,0,0,0,0,0,0,17,0,0,0
519,1400000US36047022800,36047022800,"Census Tract 228, Kings County, New York",2988,681,428,0,0,3,0,...,0,5,0,0,0,11,21,186,0,0
521,1400000US36047023000,36047023000,"Census Tract 230, Kings County, New York",3319,861,707,11,0,30,0,...,0,8,0,0,0,110,0,83,20,0
523,1400000US36047023200,36047023200,"Census Tract 232, Kings County, New York",5027,1411,652,6,0,47,0,...,0,0,9,0,0,45,0,157,0,0
525,1400000US36047023400,36047023400,"Census Tract 234, Kings County, New York",4084,981,133,56,0,0,0,...,10,0,0,0,0,114,0,112,0,0
527,1400000US36047023600,36047023600,"Census Tract 236, Kings County, New York",4526,1052,111,6,0,0,0,...,8,0,0,0,0,118,0,341,0,0
528,1400000US36047023800,36047023800,"Census Tract 238, Kings County, New York",3482,757,231,8,0,0,0,...,9,0,0,0,0,119,0,125,0,0
529,1400000US36047024000,36047024000,"Census Tract 240, Kings County, New York",3839,664,196,60,0,0,0,...,73,0,0,0,0,28,91,165,0,0
531,1400000US36047024200,36047024200,"Census Tract 242, Kings County, New York",2694,1005,108,4,0,34,5,...,0,0,0,0,0,120,0,208,0,0
533,1400000US36047024400,36047024400,"Census Tract 244, Kings County, New York",3399,1343,498,0,0,43,0,...,0,94,0,0,0,56,24,102,0,0
535,1400000US36047024600,36047024600,"Census Tract 246, Kings County, New York",2995,883,188,0,0,256,0,...,0,9,0,0,0,29,0,138,0,0
724,1400000US36047044600,36047044600,"Census Tract 446, Kings County, New York",1953,709,205,0,0,135,0,...,22,0,0,0,0,0,1,2,1,0
737,1400000US36047046400,36047046400,"Census Tract 464, Kings County, New York",2415,737,35,12,0,0,0,...,5,0,0,0,0,6,17,132,0,0
738,1400000US36047046800,36047046800,"Census Tract 468, Kings County, New York",1886,845,11,15,1,19,0,...,0,0,0,0,0,0,0,248,0,0
739,1400000US36047047000,36047047000,"Census Tract 470, Kings County, New York",2518,829,66,0,8,14,0,...,0,0,0,0,0,61,0,235,0,0
740,1400000US36047047200,36047047200,"Census Tract 472, Kings County, New York",2557,911,11,5,0,0,0,...,0,0,0,0,0,33,0,190,0,0
741,1400000US36047047400,36047047400,"Census Tract 474, Kings County, New York",2531,682,6,5,0,0,0,...,28,0,0,0,0,13,0,336,0,0
742,1400000US36047047600,36047047600,"Census Tract 476, Kings County, New York",3346,1040,256,0,0,23,0,...,0,0,0,0,22,32,0,86,0,0
744,1400000US36047047800,36047047800,"Census Tract 478, Kings County, New York",3785,1165,711,3,0,17,0,...,0,0,0,0,0,70,97,82,0,0

In [38]:
bp_2016_sum=pd.DataFrame(data=bp_languages_2016.sum()).T

In [39]:
bp_2016_sum

,Id,Id2,Geography,total_pop,english,spanish_spanish_creole,french,french_creole,italian,portuguese,...,other_asian,tagalog,other_pacific_island,navajo,other_native_na,hungarian,arabic,hebrew,african_lang,others_unspec
0,1400000US360470114001400000US36047011600140000...,1009316808000,"Census Tract 114, Kings County, New YorkCensus...",92660,23125,9444,263,20,889,101,...,297,260,66,0,34,1413,515,3881,31,0

In [ ]:
# Now let's calculate percentages
bp_2016_sum['perc_english'] = (bp_2016_sum.english) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_french'] = (bp_2016_sum.french) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_spanish'] = (bp_2016_sum.spanish_spanish_creole) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_french_creole'] = (bp_2016_sum.french_creole ) / bp_2016_sum.total_pop * 100
bp_2016_sum['italian'] = (bp_2016_sum.italian) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_portuguese'] = (bp_2016_sum.portuguese ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_german'] = (bp_2016_sum.german) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_yiddish'] = (bp_2016_sum.yiddish ) / bp_2016_sum.total_pop * 100
#astoria_sum['perc_others'] = (astoria_sum.other_west_german + astoria_sum.other_slavic + \
#                             + astoria_sum.other_hindic + astoria_sum.other_indo_european + \
#                             astoria_sum.other_asian + astoria_sum.other_pacific_island + \
#                             astoria_sum.other_native_na + astoria_sum.others_unspec) / astoria_sum.total_pop * 100
bp_2016_sum['perc_scandinavian'] = (bp_2016_sum.scandinavian_langs ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_greek'] = (bp_2016_sum.greek ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_russian'] = (bp_2016_sum.russian ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_polish'] = (bp_2016_sum.polish ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_serbo_croatian'] = (bp_2016_sum.serbo_croation ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_armenian'] = (bp_2016_sum.armenian ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_persian'] = (bp_2016_sum.persian ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_gujarati'] = (bp_2016_sum.gujarati ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_hindi'] = (bp_2016_sum.hindi ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_urdu'] = (bp_2016_sum.urdu ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_chinese'] = (bp_2016_sum.chinese ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_japanese'] = (bp_2016_sum.japanese ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_korean'] = (bp_2016_sum.korean ) / bp_2016_sum.total_pop * 100
bp_2016_sum['perc_mon_khmer_cambodian'] = (bp_2016_sum.mon_khmer_cambodian ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_hmong'] = (astoria_sum.hmong ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_thai'] = (astoria_sum.thai ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_laotian'] = (astoria_sum.laotian ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_vietnamese'] = (astoria_sum.vietnamese ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_tagalog'] = (astoria_sum.tagalog ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_navajo'] = (astoria_sum.navajo ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_hungarian'] = (astoria_sum.hungarian ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_arabic'] = (astoria_sum.arabic ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_hebrew'] = (astoria_sum.hebrew ) / astoria_sum.total_pop * 100
bp_2016_sum['perc_african_lang'] = (astoria_sum.african_lang ) / astoria_sum.total_pop * 100